posit-dev/posit-sdk-py

requirements-dev.txt, src/posit/connect/client.py, src/posit/connect/client_test.py
Just a quick PR to add a little feature we will need, but also to demonstrate how to use `responses` to stand in for the Connect API. Very straightforward to add a feature that makes an API request and then set up a test that uses a simulated response.
=> feat: pull the Connect server's version (lazily)

src/posit/connect/urls.py, src/posit/connect/users.py
I'm working on a follow-up that will reduce the boilerplate. This change gets `main` working again.
=> fix: url path resolution

src/posit/connect/config.py, src/posit/connect/config_test.py, src/posit/connect/urls.py, src/posit/connect/urls_test.py, src/posit/connect/users.py
This change moves base URL validation to the Config initialization sequence, which allows `append_path` to be called on URLs that are not base URLs.
=> fix: allow chaining paths with urls.append_path

requirements-dev.txt, src/posit/connect/users_test.py
Plus some TODOs that come out of this (I'll come back to them tomorrow, or you can feel free to push to this branch). This should exercise some of the previously untested code, and should open up a path for adding some enhancements on top.
=> test: Add tests for Users with mock responses

src/posit/connect/client.py, src/posit/connect/client_test.py
Replacement for #33, was easier to pull the changes to a fresh branch than try to rebase
Fixes #22.
=> feat: add client.me property that calls v1/user (lazily)

.github/workflows/conventional-commits.yaml
@nealrichardson and I are using conventional commits to keep the Git changelog clean. This change adds a GitHub action to verify that the pull request title uses the conventional commit syntax in the title. 
Since we are forcing "Squash and merge", developers can continue using whatever commit title they want for individual commits. By default, those commits will be squashed into the commit body.
To test the GitHub action functionality, try fixing the title of this pull request to match the style guide.
=> ci: adds action to lint conventional commits.

.github/workflows/main.yaml, Makefile
#60 updated the pull request workflow but also needed to update the main workflow, which was not triggered on the PR. This PR fixes that and modifies that workflow to run when the workflow file is touched, which should trigger it on this PR.
That said, I'm not sure why we need a separate workflow to run on main from the one we run on PRs.
=> ci: fix main workflow

.vscode/settings.json, CODE_OF_CONDUCT.md, CONTRIBUTING.md, Makefile, README.md
- **chore: updates README with additional instructions**
- **chore: adds CODE_OF_CONDUCT copied from https://github.com/posit-dev/great-tables/blob/main/CODE_OF_CONDUCT.md**
- **chore: updates README**
=> chore: updates README and adds CODE_OF_CONDUCT

examples/connect/fastapi/app.py
I was looking at this example and noticed the `get_token` method wasn't really necessary since it was just returning what it was given. If you want to keep the method though it can be simplified to just `return posit_connect_user_session_token`. The if statement is not needed.
=> style: Remove unneccesary method in FastAPI example

src/posit/connect/paginator.py, src/posit/connect/users.py, tests/posit/connect/__api__/v1/user.json, tests/posit/connect/__api__/v1/users/20a79ce3-6e87-4522-9faf-be24228800a4.json, tests/posit/connect/__api__/v1/users?page_number=1&page_size=2.json, tests/posit/connect/__api__/v1/users?page_number=2&page_size=2.json, tests/posit/connect/api.py, tests/posit/connect/test_client.py, tests/posit/connect/test_users.py
The goals here are to make the test files more readable by separating out the JSON API responses to separate files, and also to make it more natural to reuse the responses in multiple tests. I've just done this for the users mocks right now so you can review what it looks like before I go further.
It may be easier to review the commits individually. The first commit is the refactor and setup for that. In the second commit, I used it to separate out the users tests so that it was easier to test more corners of the find_one behavior, and in the process, I found and fixed a bug in its implementation.
=> chore: Factor some mock responses to JSON files and read them in with a helper

src/posit/connect/content.py, src/posit/connect/resources.py, src/posit/connect/users.py, tests/posit/connect/test_resources.py
Adding an ABC class to enforce the style choices defined in ./src/connect/README.md
=> feat: adds base class definition for resources

src/posit/connect/content.py, src/posit/connect/users.py, tests/posit/connect/test_content.py, tests/posit/connect/test_users.py
To help us move the discussion forward. I switched User to inherit from `dict` to see how that works, including adding an update method and wiring that up. I first tried `UserDict` but it messed up the sort order of the columns in the DataFrame version, and googling a bit, it sounded like it wasn't so bad to inherit from `dict` anymore, so I figured I'd try that and see how it went. Summary of what I found so far, as reflected in the test suite:
* ✅  Forwards and backwards compatibility (i.e., what happens if the API returns more or fewer fields than the class definition knows about) all works fine. If new fields appear and you haven't defined `property`s for them, it doesn't break, and you can still get at them via `[`. Missing fields also are fine, at least as long as you don't access …
=> feat: switch User and Content to inherit dict, add update method for User

.github/workflows/conventional-commits.yaml, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/resources.py, src/posit/connect/users.py, tests/posit/connect/test_resources.py, tests/posit/connect/test_users.py, tinkering.py
This change moves the `url` and `session` items from the underlying hash table used by `dict` to instance attributes. 
Subsequently, these columns no longer appear as columns when converting from a `list[Resource]` to a pandas DataFrame.
The `__setattr__` override behavior is also moved to the base `Resource` class.
Resolves #102
=> refactor: moves session and url to resource attributes

src/posit/connect/content.py, src/posit/connect/resources.py, src/posit/connect/users.py, tests/posit/connect/__api__/v1/users.json, tests/posit/connect/test_content.py, tests/posit/connect/test_resources.py, tests/posit/connect/test_users.py, tinkering.py
=> feat: adds count method to resources

src/posit/connect/client.py, src/posit/connect/users.py, tests/posit/connect/test_client.py, tests/posit/connect/test_users.py
Also fixes issues with `client.me` attribute and uses the correct HTTP method
Resolves #117 
Resolves #99
=> feat: set user attributes on update

src/posit/connect/client.py, src/posit/connect/me.py, src/posit/connect/users.py, tests/posit/connect/__api__/v1/users/a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6.json, tests/posit/connect/test_users.py
https://github.com/posit-dev/posit-sdk-py/assets/6015574/9f615141-fd6e-450f-97f3-cd192efb9658
Resolves #100
=> feat: adds user.lock() and user.unlock()

src/posit/connect/content.py, tests/posit/connect/test_content.py
Resolves #89 
Here's a recording that demonstrates the type hinting behavior in VSCode.
https://github.com/posit-dev/posit-sdk-py/assets/6015574/df0424c0-fefd-445a-8c74-6a26cdd95fa0
=> feat: adds update support to content

src/posit/connect/content.py, tests/posit/connect/test_content.py
BREAKING CHANGE: Support for passing a filter as lambda expression to `content.find` and `content.find_one` is removed. Please use client-side filtering instead. Additional filter support is planned for a future release.
=> feat!: removes filter parameter from content.find and content.find_one.

examples/connect/dash/app.py, examples/connect/shiny-python/app.py, pyproject.toml, src/posit/__init__.py, src/posit/connect/auth.py, src/posit/connect/client.py, src/posit/connect/config.py, src/posit/connect/content.py, src/posit/connect/external/databricks.py, src/posit/connect/me.py, src/posit/connect/paginator.py, src/posit/connect/urls.py, src/posit/connect/users.py, tests/posit/connect/api.py
=> docs: adds linting for docstrings

src/posit/connect/content.py, tests/posit/connect/test_content.py
=> feat: adds content create

src/posit/connect/resources.py
IPython utilizes custom i/o handlers when writing to stdout and stderr. During normal usages (.e.g, `client.users.find()`), these handlers invoke __getitem__ resulting in a warning messages for each key in the resource.
This conclusion is based on observed behavior using IPython. I haven't determined the root cause of the issue. Another fix could be checking if __getitem__, __setitem__, and __delitem__ are invoked in an IPython process.
=> fix: removes resource warning messages.

src/posit/connect/bundles.py, src/posit/connect/content.py, src/posit/connect/permissions.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/bundles.json, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/bundles/101.json, tests/posit/connect/test_bundles.py
Adds support for bundles.find, bundles.find_one, bundles.get, and bundle.delete.
Resolves #109
=> feat: adds bundles

src/posit/connect/client.py, src/posit/connect/metrics/__init__.py, src/posit/connect/metrics/usage.py, src/posit/connect/metrics/views.py, src/posit/connect/metrics/visits.py, src/posit/connect/resources.py, tests/posit/connect/metrics/test_usage.py, tests/posit/connect/metrics/test_views.py, tests/posit/connect/metrics/test_visits.py
The `metrics.views` package coalesces the existing instrumentation APIs into a single interface. The new event type `metrics.views.ViewEvent` encapsulates the `metrics.usage.UsageEvent` and `metrics.visits.VisitEvent`. The `ViewEvent` schema is a mashup of the two underlying schemas, with the exception of the `time` field on `VisitEvent`. In `ViewEvent` this field is removed and mapped to `started` and `ended`.  Otherwise, fields that do not exist in the underlying schema return `None`. 
Resolves #137
=> feat: adds metrics view events

src/posit/connect/bundles.py, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/tasks.py, tests/posit/connect/__api__/v1/tasks/jXhOhdm5OOSkGhJw.json, tests/posit/connect/test_bundles.py, tests/posit/connect/test_content.py, tests/posit/connect/test_tasks.py
Resolves #110 
Resolves #111 
Resolves #112
=> feat: adds bundle/content deploy and task management

src/posit/connect/metrics/views.py
The existing tests cover the `@property` field conditions.
=> feat: sets default value for optional event fields

src/posit/connect/content.py
Addresses the owner property of ContentItem as discussed in #165 
I ran all the steps required plus a manual test with the following output:
```python
from posit.connect import Client
with Client() as client:
all_content = client.content.find()
print(all_content[0].owner)
```
=> feat: add dataclass to represent ContentItem owner

docs/_quarto.yml, integration/tests/posit/connect/test_groups.py, src/posit/connect/client.py, src/posit/connect/groups.py, tests/posit/connect/__api__/v1/groups/6f300623-1e0c-48e6-a473-ddf630c0c0c3.json, tests/posit/connect/test_groups.py
Unit tests are sparse since we have integration tests now.
=> feat: adds groups

src/posit/connect/client.py, tests/posit/connect/metrics/test_usage.py, tests/posit/connect/test_bundles.py, tests/posit/connect/test_client.py, tests/posit/connect/test_content.py, tests/posit/connect/test_hooks.py, tests/posit/connect/test_tasks.py
Modifies the Client initialization definition to optional accept the URL and API key as position arguments.
BREAKING CHANGE: Swaps the `api_key` and `url` argument positions in Client __init__.
=> feat!: accept positional arguments when creating client

src/posit/connect/bundles.py, src/posit/connect/client.py, src/posit/connect/config.py, src/posit/connect/content.py, src/posit/connect/env.py, src/posit/connect/groups.py, src/posit/connect/me.py, src/posit/connect/metrics/shiny_usage.py, src/posit/connect/metrics/visits.py, src/posit/connect/oauth.py, src/posit/connect/permissions.py, src/posit/connect/tasks.py, src/posit/connect/urls.py, src/posit/connect/users.py, src/posit/connect/variants.py, tests/posit/connect/test_urls.py
Adds a new class, `urls.Url`, which wraps the existing `urls.create` and `urls.append` methods. This alleviates the need to `import  .urls` in most situations (see https://github.com/posit-dev/posit-sdk-py/pull/246).
The new class `urls.Url` supports Python append via the special method `__add__`. This is convenient for appending paths to the base endpoint. (e.g., `new_url = base_url + '/path'`).
=> refactor: add url class in place of urls module functions

src/posit/connect/content.py
The hash was introduced to reduce the chance of collisions with existing environment variables introduced by the user or another restart invocation. A UNIX epoch provides similar collision protection while providing additional metadata for debugging if the unset routine fails.
=> feat: replace restart environment variable hash with unix epoch

examples/connect/.gitignore, examples/connect/dash/app.py, examples/connect/dash/requirements.txt, examples/connect/fastapi/app.py, examples/connect/fastapi/requirements.txt, examples/connect/flask/app.py, examples/connect/flask/requirements.txt, examples/connect/shiny-python/app.py, examples/connect/shiny-python/requirements.txt, examples/connect/streamlit/app.py, examples/connect/streamlit/requirements.txt, src/posit/connect/external/databricks.py, tests/posit/connect/external/test_databricks.py
- Improves compatibility/usability between the Databricks python SDK and the Databricks SQL client credentials_provider interfaces: https://github.com/databricks/databricks-sql-python/issues/148#issuecomment-2271561365
- Updates all databricks viewer-auth examples to refer to the next posit-sdk release (0.4.0) in their requirements.txt
For reviewers: The important changes relevant for this PR's functionality are in `src/posit/connect/external/databricks.py`
The new credentials_strategy takes a fallback option that will be used automatically during local development, this way content can run locally and on Connect w/o requiring any code changes.
```python
import streamlit as st
from databricks import sql
from databricks.sdk.core import ApiClient, Config, databricks_cli
from …
```
=> feat!: improve compatibility with databricks sql client

.github/workflows/ci.yaml, examples/connect/dash/app.py, examples/connect/fastapi/app.py, examples/connect/flask/app.py, examples/connect/shiny-python/app.py, examples/connect/streamlit/app.py, src/posit/connect/auth.py, src/posit/connect/external/databricks.py, tests/posit/connect/external/test_databricks.py
Run `make fmt` in CI to catch formatting issues. Here is an example failure: https://github.com/posit-dev/posit-sdk-py/actions/runs/10307772634/job/28533756390
Related to #254
=> ci: add format check

src/posit/connect/content.py, src/posit/connect/groups.py, src/posit/connect/metrics/shiny_usage.py, src/posit/connect/metrics/usage.py, src/posit/connect/metrics/visits.py, src/posit/connect/permissions.py, src/posit/connect/tasks.py, src/posit/connect/users.py, tests/posit/connect/test_users.py
Various methods are defined with improper variadic positional and keyword arguments. The original intention for `@overload` signatures was to provide type support for pass-throughs to API query parameters or JSON arguments. Along the way, *args was introduced to these methods, assuming we wanted to match the dict function signature. This isn't very clear in practice since passing SupportsKeysAndGetItem typed variables is rare. Therefore, the *args part of the function signature is removed wherever possible. In the update(self, *args, **kwargs), we cannot remove *args since we inherit from dict, and dict enforces this method signature.
=> fix: use correct args and kwargs definitions

.github/workflows/ci.yaml, integration/Makefile
Add the latest Connect release, v2024.08.0, to the integration test suite.
=> ci: add Connect v2024.08.0 to integration test suite

src/posit/__init__.py, src/posit/connect/client.py, src/posit/connect/groups.py, src/posit/connect/resources.py, src/posit/connect/users.py
This change fixes errors and warnings issued by Pyright. 
The update method is added to the base Resource class, which fixes type-checking issues against MutableMapping.
=> fix: correct type signatures according to pyright

Makefile, pyproject.toml
The **/*.py syntax is evaluated incorrectly and fails silently.
=> fix: use correct mypy syntax

integration/Makefile, vars.mk
pipefail is required to capture the pytest exit code
=> build: set make shell to bash.

.github/workflows/release.yaml, .github/workflows/site.yaml
Host the production documentation site on GitHub pages instead of Netlify.
=> docs: host production site on github pages

src/posit/connect/bundles.py, src/posit/connect/content.py, src/posit/connect/env.py, src/posit/connect/groups.py, src/posit/connect/metrics/shiny_usage.py, src/posit/connect/metrics/visits.py, src/posit/connect/oauth/integrations.py, src/posit/connect/oauth/oauth.py, src/posit/connect/oauth/sessions.py, src/posit/connect/permissions.py, src/posit/connect/resources.py, src/posit/connect/tasks.py, src/posit/connect/users.py, src/posit/connect/variants.py, tests/posit/connect/test_content.py, tests/posit/connect/test_users.py
Remove all `@property` annotated methods used for direct field access on concrete resources. To maintain backward compatibility, a new `__getattr__` implementation is added to Resource. This implementation invokes `__getitem__` when the key exists in self. A noisy deprecation warning alerts users that this functionality will be removed in v1.0.0.
=> feat: deprecates field access by attribute.

Makefile, pyproject.toml
Remove glob expressions from Ruff calls. These expressions are inconsistent between shells and cause unexpected behavior.
Update the Ruff configuration in pyproject.toml to also exclude the integration/resources directory, which includes additional Python projects used for testing bundles.
=> build: fix ruff config

Makefile, pyproject.toml, requirements-dev.txt, src/posit/connect/content.py, src/posit/connect/external/databricks.py, src/posit/connect/external/snowflake.py
When analyzing overload definitions, Pyright does a better job at understanding the conventions we have established. This is due to how Pyright has decided to interpret PEP-484. Additional details are available here: https://github.com/microsoft/pyright/blob/main/docs/type-concepts-advanced.md#overloads
Additionally, Pyright discovered a few issues with types, which are addressed in this change.
=> build: use pyright as static type checker

integration/tests/posit/connect/oauth/test_associations.py, integration/tests/posit/connect/oauth/test_integrations.py, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/oauth/associations.py, src/posit/connect/oauth/integrations.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/oauth/integrations/associations.json, tests/posit/connect/__api__/v1/oauth/integrations/22644575-a27b-4118-ad06-e24459b05126/associations.json, tests/posit/connect/oauth/test_associations.py, tests/posit/connect/oauth/test_integrations.py, tests/posit/connect/test_content.py
Adds support for requesting and updating oauth associations through the Connect API.
=> feat: Implements OAuth association API resource

integration/Makefile
This changes the behavior of the `make it` command from "./Makefile".
The `make it` command is only used for convenience. Otherwise, the "./integration/Makefile" is used directly for integration testing.
=> build: change default to latest

integration/tests/posit/connect/test_content.py, src/posit/connect/content.py, tests/posit/connect/test_content.py
Simplifies or, in most cases, corrects the overload signature. Variable names and documentation are updated along the way.
- Renames `kwargs` based on context. The variable name `conditions` is introduced for querying methods. The variable name `attributes` is introduced for record manipulation. This also signifies that this is not a passthrough method. 
- Documentation is updated to reflect the current state of Posit Connect.
- Removes deprecations for field names in integration tests.
Resolves #140
=> fix: content overload signatures

integration/tests/posit/connect/test_content.py, integration/tests/posit/connect/test_groups.py, src/posit/connect/bundles.py, src/posit/connect/content.py, src/posit/connect/env.py, src/posit/connect/groups.py, src/posit/connect/metrics/shiny_usage.py, src/posit/connect/metrics/visits.py, src/posit/connect/permissions.py, src/posit/connect/resources.py, src/posit/connect/tasks.py, src/posit/connect/users.py, src/posit/connect/variants.py, tests/posit/connect/test_bundles.py, tests/posit/connect/test_client.py, tests/posit/connect/test_content.py, tests/posit/connect/test_groups.py, tests/posit/connect/test_permissions.py, tests/posit/connect/test_tasks.py, tests/posit/connect/test_users.py
BREAKING CHANGE: removes support for accessing resource fields using
`__getattr__` (e.g., `user.username`). Use `__getitem__` instead (e.g.,
`user["username"]`.
depends on #265 and #266
closes #262
=> refactor!: drop support field access by attribute. 

pyproject.toml, requirements.txt, src/posit/connect/client.py, src/posit/connect/context.py, tests/posit/connect/external/test_databricks.py, tests/posit/connect/external/test_snowflake.py, tests/posit/connect/oauth/test_associations.py, tests/posit/connect/oauth/test_integrations.py, tests/posit/connect/oauth/test_oauth.py, tests/posit/connect/oauth/test_sessions.py, tests/posit/connect/test_client.py, tests/posit/connect/test_context.py
Adds a new decorator, `@context.requires`, which asserts version compatibility when the server version is known. The check is skipped if the server version is unknown (e.g., the Connect configuration disables version information).
Also marks the OAuth API with a '2024.08.0' requirement.
Closes #272
=> feat: add version check support

integration/Makefile, integration/tests/posit/connect/test_users.py, pyproject.toml, requirements.txt, src/posit/connect/content.py, src/posit/connect/paginator.py, src/posit/connect/users.py
Adds create user support for local authentication providers (e.g., 'ldap', 'oauth2', 'pam', 'password', 'proxy', or 'saml').
Closes #113
Closes #225
=> feat: add create local user support

integration/tests/posit/connect/test_jobs.py, src/posit/connect/content.py, src/posit/connect/context.py, src/posit/connect/jobs.py, src/posit/connect/resources.py, src/posit/connect/vanities.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/jobs.json, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/jobs/tHawGvHZTosJA2Dx.json, tests/posit/connect/test_content.py, tests/posit/connect/test_jobs.py
Adds job support.
The mixin pattern is continued, and a 'jobs' property is added to `ContentItem.`
A new abstraction around resources called `Active` is introduced. This abstraction begins a transition to a more idiomatic approach to interacting with collections. Similar to how printing a `Resource` shows a `dict`, the `ActiveSequence` shows a familiar `List[dict]` representation. The `ActiveFinderMethods` supports the `find` and `find_by` methods. This is inspired by this Ruby on Rails module https://api.rubyonrails.org/classes/ActiveRecord/FinderMethods.html. Ideally, this separation of concerns provides a straightforward way to compose bindings in the future and reduces the amount of duplication across implementations.
Additional background may be found here …
=> feat: add jobs

src/posit/connect/resources.py
Removes the cache layer from finder methods to reduce the complexity of propagating query parameters.
When passing query parameters through finder methods, it is difficult to manage the cache if we wish to have it reflect the user's query state. For example, when calling `packages.find_by(name='posit-sdk)',` what should `packages._data` return on the next call?
=> refactor: removes cache layer from active sequence

integration/tests/posit/connect/__init__.py, integration/tests/posit/connect/test_content.py, pyproject.toml, src/posit/connect/content.py, tests/posit/connect/external/test_databricks.py, tests/posit/connect/metrics/test_shiny_usage.py, tests/posit/connect/metrics/test_usage.py, tests/posit/connect/metrics/test_visits.py, tests/posit/connect/oauth/test_associations.py, tests/posit/connect/oauth/test_integrations.py, tests/posit/connect/oauth/test_oauth.py, tests/posit/connect/test_bundles.py, tests/posit/connect/test_client.py, tests/posit/connect/test_groups.py, tests/posit/connect/test_permissions.py, tests/posit/connect/test_tasks.py, tests/posit/connect/test_users.py, tests/posit/connect/test_vanities.py
Pylance was flagging many lines. Added `tests` folder into the type checker.
=> style: Lint testing folders

src/posit/connect/resources.py
The` __getattr__` method should always raise an `AttributeError` if the value does not exist instead of returning `None`. The existing implementation causes issues when converting to a Pandas `DataFrame`.
This error was introduced in the 0.5.0 release.
=> fix: raise AttributeError instead of returning None on __getattr__

.github/workflows/ci.yaml, integration/Makefile, integration/compose.yaml, integration/tests/posit/connect/__init__.py, integration/tests/posit/connect/test_jobs.py, integration/tests/posit/connect/test_packages.py, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/context.py, src/posit/connect/packages.py, src/posit/connect/paginator.py, src/posit/connect/resources.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/packages.json, tests/posit/connect/__api__/v1/packages.json, tests/posit/connect/external/test_databricks.py, tests/posit/connect/external/test_snowflake.py, tests/posit/connect/oauth/test_associations.py, tests/posit/connect/oauth/test_integrations.py, tests/posit/connect/oauth/test_oauth.py, tests/posit/connect/oauth/test_sessions.py, tests/posit/connect/test_client.py, tests/posit/connect/test_context.py, tests/posit/connect/test_jobs.py, tests/posit/connect/test_packages.py
Adds packages support.
Resolves #304 
Requires https://github.com/rstudio/connect/issues/28227
=> feat: add packages and content packages

integration/tests/posit/connect/test_content_item_permissions.py, integration/tests/posit/connect/test_users.py, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/context.py, src/posit/connect/groups.py, src/posit/connect/me.py, src/posit/connect/permissions.py, src/posit/connect/users.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/permissions.json, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/permissions/59.json, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/permissions/94.json, tests/posit/connect/__api__/v1/groups.json, tests/posit/connect/__api__/v1/groups/6f300623-1e0c-48e6-a473-ddf630c0c0c3.json, tests/posit/connect/__api__/v1/groups/6f300623-1e0c-48e6-a473-ddf630c0c0c3/members.json, tests/posit/connect/__api__/v1/groups/empty-group-guid/members.json, tests/posit/connect/__api__/v1/groups/groups.json, tests/posit/connect/test_client.py, tests/posit/connect/test_content.py, tests/posit/connect/test_context.py, tests/posit/connect/test_groups.py, tests/posit/connect/test_permissions.py, tests/posit/connect/test_users.py
Fixes #340
Related https://github.com/rstudio/connect/issues/28176
Added
* `Group`
* `Group.members.find()` - Retrieve all users for a given group
* `Group.members.add(user)` - Add user to a group
* `Group.members.delete(user)` - Remove user form a group
* `User`
* `Users.groups.find()` - Retrieve all groups for a given user
* `User.groups.add(group)` - Add user to a group
* `User.groups.delete(group)` - Remove user from a group
* `Context` class added `self.ctx = weakref.proxy(client)` 
* A weakref was used as `Client -> Context -> Client` circular dependency is made quickly. By having the `Context -> Client` be weak, then the `Context` will only disappear once the parent `Client` wants to be gc'd.
* Permissions
* `.destroy(*permissions)` was changed to `.destroy(permission)` to follow …
=> feat: Add `User.groups` and `Group.members`

src/posit/connect/permissions.py, tests/posit/connect/test_permissions.py
Fixes https://github.com/posit-dev/posit-sdk-py/issues/342
Related: https://github.com/rstudio/connect/issues/28825
- Not needed as cosmetic unit testing should cover it
=> feat: Add `Permission.create(*args:User | Group)` support

docs/_quarto.yml, src/posit/connect/content.py, src/posit/connect/external/databricks.py, src/posit/connect/external/snowflake.py, src/posit/connect/oauth/__init__.py, src/posit/connect/oauth/oauth.py, tests/posit/connect/external/test_databricks.py, tests/posit/connect/oauth/test_oauth.py
This PR adds a new function to the oauth tooling. It knows how to craft a request against the credential exchange endpoint that can interface with client credential flows. This supports service-account-like oauth interactions. 
Connect sets an environment variable called `CONNECT_CONTENT_SESSION_TOKEN` which can be used by the executing content when making the request. This means that the syntax for using this new credential exchange function is slightly different. 
This PR also adds the databricks extensions needed to use this new oauth exchange flow when interfacing with databricks resources. 
This feature won't land in Connect until the upcoming release gets published - I don't know how we typically queue up work like this in sync with product releases.
=> feat: Add client credential oauth integration support + related databricks helpers to SDK

integration/tests/posit/connect/test_tags.py, src/posit/connect/tags.py, tests/posit/connect/__api__/v1/tags/33-patched.json, tests/posit/connect/test_tags.py
Fixes #350 
Missed method in #346 . Discovered from #162 top comment
=> feat: Add `Tag.update() -> Tag` method

integration/Makefile, integration/compose.yaml
Adds PYTEST_ARGS environment variable `integration/Makefile`. This allows additional arguments to be passed to pytest at runtime. For example, `PYTEST_ARGS='-k TestJobs' make latest` will execute as `pytest -k TestJobs`.
This change also includes other quality-of-life improvements to the Makefile.
=> build: add PYTEST_ARGS to integration/Makefile.

integration/tests/posit/connect/test_system.py, src/posit/connect/client.py, src/posit/connect/groups.py, src/posit/connect/packages.py, src/posit/connect/system.py, src/posit/connect/users.py, tests/posit/connect/__api__/v1/system/caches/runtime.json, tests/posit/connect/test_system.py
Fixes #337 
Example usage:
```python
from posit.connect import Client
client = Client()
runtime_caches = client.system.caches.runtime.find()
first_runtime_cache = runtime_caches[0]
task = first_runtime_cache.destroy(dry_run=True)
task.wait_for()
```
=> feat: Add support for system cache runtime

integration/tests/posit/connect/test_tags.py, src/posit/connect/_utils.py, src/posit/connect/content.py, src/posit/connect/env.py, src/posit/connect/metrics/usage.py, src/posit/connect/repository.py, src/posit/connect/resources.py, src/posit/connect/tags.py, tests/posit/connect/test_packages.py, tests/posit/connect/test_tags.py
Other changes: 
* Added `update_dict_values(obj, **kwargs)` to update the dict values of an object from https://github.com/posit-dev/posit-sdk-py/pull/366#discussion_r1887845267
This is the last `.update()` that needs to be fixed.
=> refactor: `Tag.update()` should return `None`

src/posit/connect/client.py
Added a couple more examples to make it clearer to people using the SDK how this function works to generate a visitor client.
=> chore: added more docs/examples to with_user_session_token

.github/workflows/ci.yaml
Updates CI to use GHCR image repository instead of Docker Hub.
=> test: use ghcr image repository

.github/workflows/ci.yaml
Not needed because this repository only uses public images.
Reverts #386.
=> ci: remove ghcr login

.github/workflows/ci.yaml, integration/Makefile
Reads the supported Connect versions from `./integration/Makefile` via the `make print-versions` command.
=> ci: define matrix input using makefile output

src/posit/connect/client.py, src/posit/connect/external/aws.py, src/posit/connect/oauth/oauth.py, tests/posit/connect/external/test_aws.py, tests/posit/connect/oauth/test_oauth.py
- Refactored supported token types into a string enum
- Added aws creds helper to properly decode the value from the Connect credential exchange endpoint
=> feat: added standard token type enum; added aws_creds helper

src/posit/connect/client.py, src/posit/connect/paginator.py, src/posit/connect/resources.py
The Connect Packages API (v1/packages) supports uncapped page size. By increasing the page size from the default of 500 to 1,000,000, there is a significant speed up when fetching all packages. This is due to a reduction in the number of round trips to the Connect server. The tradeoff is a larger payload. Since the Python requests package does not limit the  HTTP GET request-response body size, we are unconcerned with the larger payload.
=> feat: speed up the packages api

.gitignore, integration/.gitignore
Adding `*.lic` to `.gitignore` so that accidentally committing license files requires additional steps.
=> chore: Add `*.lic` to `.gitignore`

src/posit/connect/external/aws.py, src/posit/connect/oauth/oauth.py, tests/posit/connect/external/test_aws.py, tests/posit/connect/oauth/test_oauth.py
Similar to existing helper for Viewer integrations but the content session token counterpart. 
Usage example in docstring for function.
Tests updated.
=> feat: Add support for AWS integration content session token exchange

.github/workflows/ci.yaml, .github/workflows/coverage.yaml, .github/workflows/release.yaml, .github/workflows/site.yaml, docs/Makefile, integration/Makefile
- ci: fixes `site.yaml` action
- ci: updates imported actions to latest version
- build: remove use of `uv run --with` since it no longer supports bash
- test: add Connect v2025.04.0 to test suite
- ci: update Node to v22
=> ci: fixes issues with `site.yaml` action

.github/workflows/site.yaml, integration/tests/posit/connect/test_bundles.py, src/posit/connect/bundles.py, tests/posit/connect/test_bundles.py
Adds `active()` method to `Bundles` class to retrieve the currently active bundle.
Resolves #380
=> feat: add method to retrieve active bundle

src/posit/connect/metrics/hits.py, src/posit/connect/metrics/metrics.py, src/posit/connect/metrics/rename_params.py, src/posit/connect/metrics/shiny_usage.py, src/posit/connect/metrics/visits.py, src/posit/connect/resources.py, tests/posit/connect/__api__/v1/instrumentation/content/hits.json, tests/posit/connect/metrics/test_hits.py, tests/posit/connect/metrics/test_rename_params.py, tests/posit/connect/metrics/test_shiny_usage.py, tests/posit/connect/metrics/test_visits.py
Add support support for Posit Connect's content hits endpoint (`GET /v1/instrumentation/content/hits`)
Closes #403 
- Implementation lives in `metrics/hits.py`
- `from` and `to` parameters are named `start` and `end` in Python to work around reserved keywords. The `rename_params` function shared across all metrics classes has been collapsed into a single function.
- Tests have been added which cover all of the new functionality.
=> feat: add `metrics.hits`, with support for new `instrumentation/content/hits` endpoint

integration/Makefile, integration/tests/posit/connect/oauth/test_associations.py, integration/tests/posit/connect/test_groups.py, tests/posit/connect/test_client.py, tests/posit/connect/test_hooks.py
Starting in 2025.05.0, a default integration is created by Connect. We want to destroy that integration before running the test suite.
=> test(fix): destroy the default integration before testing

integration/tests/posit/connect/test_content.py, src/posit/connect/content.py, tests/posit/connect/test_content.py
Adds `include` param support for `content.get()`
- Add the param support, opting to hardcode it so it is always used
- Add unit test
- Add integration test
- Also manually verified by testing locally against a live Connect instance
Replaces previous fork PR: https://github.com/posit-dev/posit-sdk-py/pull/416
=> feat: extend content.get() to automatically use `include` param

src/posit/connect/tasks.py, tests/posit/connect/test_tasks.py
Implements an improved task polling mechanism with configurable wait time. This helps to minimize resource consumption on the Connect server while still providing responsive feedback.
Resolves #184
=> feat: improve task polling

integration/tests/posit/connect/oauth/test_associations.py, src/posit/connect/client.py, src/posit/connect/content.py, src/posit/connect/external/aws.py, src/posit/connect/external/databricks.py, src/posit/connect/external/snowflake.py, src/posit/connect/oauth/associations.py, src/posit/connect/oauth/integrations.py, src/posit/connect/oauth/oauth.py, src/posit/connect/oauth/types.py, src/posit/connect/resources.py, tests/posit/connect/__api__/v1/content/f2f37341-e21d-3d80-c698-a935ad614066/oauth/integrations/associations.json, tests/posit/connect/__api__/v1/oauth/integrations.json, tests/posit/connect/oauth/test_associations.py, tests/posit/connect/oauth/test_integrations.py, tests/posit/connect/oauth/test_oauth.py, tests/posit/connect/test_content.py, tests/posit/connect/test_resources.py
- Adds in support for the optional audience parameter for the credential exchange endpoint to determine which integration to use
- Removes "only 1 association" constraint on updating content's oauth integration associations.
- Adds `find_by` helper method for integrations and associations to allow a user to search available integrations (globally or scoped to a specific piece of content) to get the GUID for the integration they need dynamically.
=> feat: add optional audience parameter to credential exchange related methods
